config/routes.rb
Rails.application.routes.draw do
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end
  root to: 'services#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create 

    # Setting up a Stripe Session for peyment.
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: "Monthly Course",
        description: "digital textbook with mentor's support.",
        amount: 1000,
        currency: "usd",
        quantity: 1
      }],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )

    respond_to do |format|
      format.js # render create.js.erb
    end

    
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel
    
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>')

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then (function(result) {
  console.log(result.error.message);
});

app/views/checkout/success.html.erb
<h1>購入が完了しました</h1>

<div>ご登録のメールアドレスに詳細をメールを送信しました。詳細はそちらをご確認ください</div>

<%= link_to 'コース一覧に戻る', root_path %>

<%#= debug @session %>
<%#= debug @payment_intent %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandingPageProgramming</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/services/index.html.erb
<h1>コース一覧</h1>

<div>1週間でサイト運営者コース</div>
<%= image_tag 'https://fecayman.com/wp-content/uploads/2019/12/top11.png', width: "440", height: "200" %>
<%= button_to '購入', checkout_create_path, method: :post, remote: true %> <%# 購入商品のidなども引き渡すことができる → ,params: {id: product.id} %>